---

- name: Install secure arch linux environment
  hosts: hosts
  connection: local
  become: True

  roles:
    - { role: network, tags: ['network'] }
    - { role: editor, tags: ['editor'] }
    - { role: grub, tags: ['grub'], when: "bootloader == 'grub'"}
    - { role: syslinux, tags: ['syslinux'], when: "bootloader == 'syslinux'"}
    - { role: browsers, tags: ['browsers'] }    
    - { role: kernel, tags: ['kernel'] }
    - { role: base, tags: ['base'] }
    - { role: shell, tags: ['shell'] }
    - { role: terminal, tags: ['terminal'] }
    - { role: firewall, tags: ['firewall'] }
    - { role: dotfiles, tags: ['dotfiles'] }
    
    - { role: mail, tags : ['mail'] }
    - { role: firejail, tags: ['firejail'] }
    - { role: windowmanager, tags: ['windowmanager'] }
    - { role: keepass, tags: ['keepass'] }
    - { role: macspoof, tags: ['macspoof'], when: "system.macspoof == 'enabled'"}
    - { role: sound, tags : ['sound'] }
    - { role: mail, tags : ['mail'] }
    - { role: messengers, tags : ['messengers'] }
    - { role: tizonia, tags : ['tizonia'] }
